### ISSUE TITLE
yarn start/test lead to missing dependency error

### ISSUE THREAD

**Issue by halas** [crollalowis/cl-ui#22]
When I try to run `yarn start` or `yarn test` I get missing `babel-jest` dependency error.

**Comment by rhoffmann** [comment]
oh yes, this needs documentation. you need to create and .env file, there is an `example.env` to copy

**Comment by halas** [comment]
The readme has also wrong port, it is 6006

**Comment by halas** [comment]
I will make a pr

**Comment by rhoffmann** [comment]
please

**Comment by halas** [comment]
ok, but even with env file, now yarn start complains:
```
Could not find a ruequired file 
Name: index.html
```
Any ideas why is that?

**Comment by rhoffmann** [comment]
yes. there is none :D
its basically only the storybook. `dev` -> `storybook` and `build` -> `build-storybook`. you could map start / dev / build if you like.

**Comment by rhoffmann** [comment]
so 
`start -> dev`
`dev -> storybook`
`build -> build-storybook`

**Comment by halas** [comment]
and we don't need eject, do we?

**Comment by rhoffmann** [comment]
maybe someday, lets keep it
